# Site settings
title: Code - 44
header-img: img/home-bg.png
email: matthew.daly40@gmail.com
copyright_name: Matthew-Daly
description: > # this means to ignore newlines until "baseurl:"
  Or: Exercises in Frustration
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Matthew-Daly
learn_profile: Matthew-Daly
email_username: matthew.daly40@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
